name: Build

on:
  push:
    branches:
      - 'master'
      - 'v0.11'
      - 'root'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  QT_VERSION: "5.15.2"
  OBS_VERSION: "27.0.0-ci"
  OBSDEPS_VERSION: "27.0.0"
  LIBAOM_VERSION: "3.2.0.0"

jobs:
  windows:
    name: "Windows 64-bit"
    strategy:
      fail-fast: true
      matrix:
        runner: [ windows-2019 ]
        include:
          - runner: windows-2019
            id: windows-2019
            windows_sdk: "10.0.18362.0"
            cmake_generator: "Visual Studio 16 2019"
            cmake_generator_platform: "x64"
    runs-on: ${{ matrix.runner }}
    env:
      CMAKE_GENERATOR: ${{ matrix.cmake_generator }}
      CMAKE_GENERATOR_PLATFORM: ${{ matrix.cmake_generator_platform }}
      CMAKE_GENERATOR_TOOLSET: "host=x64"
      CMAKE_SYSTEM_VERSION: ${{ matrix.windows_sdk }}
    steps:
    - name: "Clone"
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: "libobs: Cache"
      if: ${{ github.event_name != 'pull_request' }}
      uses: actions/cache@v2
      with:
        path: |
          build/temp/libobs-download
          build/temp/libobs-build
          build/temp/libobs-src
        key: libobs-${{ matrix.id }}-${{ env.OBS_VERSION }}-${{ env.DOWNLOAD_OBS_HASH }}
    - name: "obsdeps: Cache"
      if: ${{ github.event_name != 'pull_request' }}
      uses: actions/cache@v2
      with:
        path: |
          build/temp/obsdeps-download
          build/temp/obsdeps-build
          build/temp/obsdeps-src
        key: obsdeps-${{ matrix.id }}-${{ env.OBSDEPS_VERSION }}-${{ env.DOWNLOAD_OBSDEPS_HASH }}
    - name: "qt: Cache"
      if: ${{ github.event_name != 'pull_request' }}
      uses: actions/cache@v2
      with:
        path: |
          build/temp/qt-download
          build/temp/qt-build
          build/temp/qt-src
        key: qt-${{ matrix.id }}-${{ env.OBSDEPS_VERSION }}-${{ env.QT_VERSION }}
    - name: "libaom: Cache"
      if: ${{ github.event_name != 'pull_request' }}
      uses: actions/cache@v2
      id: libaom-cache
      with:
        path: |
          build/libaom
        key: libaom-${{ matrix.id }}-${{ env.LIBAOM_VERSION }}
    - name: "libaom: Install"
      if: ${{ steps.libaom-cache.outputs.cache-hit != 'true' }}
      id: libaom-install
      shell: bash
      run: |
        curl -L -o "aom.7z" "https://github.com/Xaymar/aom/releases/download/v${{ env.LIBAOM_VERSION }}/aom-windows-64-shared.7z"
        7z x -y -o"build/libaom/" "aom.7z"
    - name: "StreamFX: Configure"
      shell: bash
      run: |
        cmake -H. -B"build/temp" \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_INSTALL_PREFIX="build/distrib" \
          -DPACKAGE_NAME="streamfx-${{ matrix.id }}" \
          -DPACKAGE_PREFIX="build/package" \
          -DDOWNLOAD_OBS_URL="https://github.com/Xaymar/obs-studio/releases/download/${{ env.OBS_VERSION }}/obs-studio-x64-0.0.0.0-windows-x86-64.7z" \
          -DDOWNLOAD_OBS_HASH="SHA256=EBF9853C8A553E16ECBCA22523F401E6CF1EB2E8DA93F1493FEF41D65BD06633" \
          -DDOWNLOAD_OBSDEPS_URL="https://github.com/Xaymar/obs-studio/releases/download/${{ env.OBSDEPS_VERSION }}/deps-windows-x86.7z" \
          -DDOWNLOAD_OBSDEPS_HASH="SHA256=B4AED165016F0B64A7E8B256CCC12EAF8AF087F61B0B239B9D3D00277485B5B5" \
          -DDOWNLOAD_QT=ON \
          -DDOWNLOAD_QT_URL="https://github.com/Xaymar/obs-studio/releases/download/${{ env.OBSDEPS_VERSION }}/qt-${{ env.QT_VERSION }}-windows-x86-64.7z" \
          -DDOWNLOAD_QT_HASH="SHA256=109B9C21EF165B0C46DFAA9AD23124F2070ED4D74207C4AFB308183CB8D43BDD" \
          -DAOM_PATH="build/libaom/"
    - name: "StreamFX: Build"
      shell: bash
      run: |
        cmake --build "build/temp" --config RelWithDebInfo --target INSTALL
    - name: "StreamFX: Package (Install Prerequisites)"
      run: |
        curl "-kL" "https://cdn.xaymar.com/ci/innosetup-6.1.2.exe" "-f" "--retry" "5" "-o" "inno.exe"
        .\inno.exe /VERYSILENT /SP- /SUPPRESSMSGBOXES /NORESTART
    - name: "StreamFX: Package"
      shell: bash
      run: |
        mkdir build/package
        cmake --build "build/temp" --config RelWithDebInfo --target PACKAGE_7Z
        cmake --build "build/temp" --config RelWithDebInfo --target PACKAGE_ZIP
    - name: "StreamFX: Package Installer"
      shell: cmd
      run: |
        echo '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" /V10 ".\build\temp\installer.iss"'
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" /V10 ".\build\temp\installer.iss"
    - name: "Artifacts"
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.id }}
        path: build/package
